/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAwardsRouteImport } from './routes/_auth/awards'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as AuthMypageIndexRouteImport } from './routes/_auth/mypage/index'
import { Route as AuthMypageEditRouteImport } from './routes/_auth/mypage/edit'
import { Route as AuthMypagePasswordChangeRouteImport } from './routes/_auth/mypage/password-change'
import { Route as AuthNewsIndexRouteImport } from './routes/_auth/news/index'
import { Route as AuthNewsGalleryRouteImport } from './routes/_auth/news/gallery'
import { Route as AuthNoticeIndexRouteImport } from './routes/_auth/notice/index'
import { Route as AuthNoticeIdRouteImport } from './routes/_auth/notice/$id'
import { Route as AuthNoticeWriteRouteImport } from './routes/_auth/notice/write'
import { Route as AuthTrainingIndexRouteImport } from './routes/_auth/training/index'
import { Route as AuthTrainingIdRouteImport } from './routes/_auth/training/$id'
import { Route as AuthTrainingWriteRouteImport } from './routes/_auth/training/write'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthUsersIdRouteImport } from './routes/_auth/users/$id'
import { Route as AuthVideosIndexRouteImport } from './routes/_auth/videos/index'
import { Route as AuthVideosIdRouteImport } from './routes/_auth/videos/$id'
import { Route as AuthNewsYearIndexRouteImport } from './routes/_auth/news/$year/index'
import { Route as AuthNewsYearIdRouteImport } from './routes/_auth/news/$year/$id'
import { Route as AuthNewsYearWriteRouteImport } from './routes/_auth/news/$year/write'
import { Route as AuthVideosFullpageIndexRouteImport } from './routes/_auth/videos/fullpage/index'
import { Route as AuthVideosFullpageJobIdRouteImport } from './routes/_auth/videos/fullpage/$jobId'
import { Route as AuthNewsYearGalleryIndexRouteImport } from './routes/_auth/news/$year/gallery/index'
import { Route as AuthNewsYearGalleryWriteRouteImport } from './routes/_auth/news/$year/gallery/write'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAwardsRoute = AuthAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AuthRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const AuthMypageIndexRoute = AuthMypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMypageEditRoute = AuthMypageEditRouteImport.update({
  id: '/mypage/edit',
  path: '/mypage/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMypagePasswordChangeRoute =
  AuthMypagePasswordChangeRouteImport.update({
    id: '/mypage/password-change',
    path: '/mypage/password-change',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthNewsIndexRoute = AuthNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsGalleryRoute = AuthNewsGalleryRouteImport.update({
  id: '/news/gallery',
  path: '/news/gallery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNoticeIndexRoute = AuthNoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNoticeIdRoute = AuthNoticeIdRouteImport.update({
  id: '/notice/$id',
  path: '/notice/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNoticeWriteRoute = AuthNoticeWriteRouteImport.update({
  id: '/notice/write',
  path: '/notice/write',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrainingIndexRoute = AuthTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrainingIdRoute = AuthTrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrainingWriteRoute = AuthTrainingWriteRouteImport.update({
  id: '/training/write',
  path: '/training/write',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIdRoute = AuthUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVideosIndexRoute = AuthVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVideosIdRoute = AuthVideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsYearIndexRoute = AuthNewsYearIndexRouteImport.update({
  id: '/news/$year/',
  path: '/news/$year/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsYearIdRoute = AuthNewsYearIdRouteImport.update({
  id: '/news/$year/$id',
  path: '/news/$year/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsYearWriteRoute = AuthNewsYearWriteRouteImport.update({
  id: '/news/$year/write',
  path: '/news/$year/write',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVideosFullpageIndexRoute = AuthVideosFullpageIndexRouteImport.update({
  id: '/videos/fullpage/',
  path: '/videos/fullpage/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVideosFullpageJobIdRoute = AuthVideosFullpageJobIdRouteImport.update({
  id: '/videos/fullpage/$jobId',
  path: '/videos/fullpage/$jobId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsYearGalleryIndexRoute =
  AuthNewsYearGalleryIndexRouteImport.update({
    id: '/news/$year/gallery/',
    path: '/news/$year/gallery/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthNewsYearGalleryWriteRoute =
  AuthNewsYearGalleryWriteRouteImport.update({
    id: '/news/$year/gallery/write',
    path: '/news/$year/gallery/write',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/awards': typeof AuthAwardsRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/mypage/edit': typeof AuthMypageEditRoute
  '/mypage/password-change': typeof AuthMypagePasswordChangeRoute
  '/news/gallery': typeof AuthNewsGalleryRoute
  '/notice/$id': typeof AuthNoticeIdRoute
  '/notice/write': typeof AuthNoticeWriteRoute
  '/training/$id': typeof AuthTrainingIdRoute
  '/training/write': typeof AuthTrainingWriteRoute
  '/users/$id': typeof AuthUsersIdRoute
  '/videos/$id': typeof AuthVideosIdRoute
  '/mypage/': typeof AuthMypageIndexRoute
  '/news/': typeof AuthNewsIndexRoute
  '/notice/': typeof AuthNoticeIndexRoute
  '/training/': typeof AuthTrainingIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/videos/': typeof AuthVideosIndexRoute
  '/news/$year/$id': typeof AuthNewsYearIdRoute
  '/news/$year/write': typeof AuthNewsYearWriteRoute
  '/videos/fullpage/$jobId': typeof AuthVideosFullpageJobIdRoute
  '/news/$year/': typeof AuthNewsYearIndexRoute
  '/videos/fullpage/': typeof AuthVideosFullpageIndexRoute
  '/news/$year/gallery/write': typeof AuthNewsYearGalleryWriteRoute
  '/news/$year/gallery/': typeof AuthNewsYearGalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/awards': typeof AuthAwardsRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/mypage/edit': typeof AuthMypageEditRoute
  '/mypage/password-change': typeof AuthMypagePasswordChangeRoute
  '/news/gallery': typeof AuthNewsGalleryRoute
  '/notice/$id': typeof AuthNoticeIdRoute
  '/notice/write': typeof AuthNoticeWriteRoute
  '/training/$id': typeof AuthTrainingIdRoute
  '/training/write': typeof AuthTrainingWriteRoute
  '/users/$id': typeof AuthUsersIdRoute
  '/videos/$id': typeof AuthVideosIdRoute
  '/mypage': typeof AuthMypageIndexRoute
  '/news': typeof AuthNewsIndexRoute
  '/notice': typeof AuthNoticeIndexRoute
  '/training': typeof AuthTrainingIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/videos': typeof AuthVideosIndexRoute
  '/news/$year/$id': typeof AuthNewsYearIdRoute
  '/news/$year/write': typeof AuthNewsYearWriteRoute
  '/videos/fullpage/$jobId': typeof AuthVideosFullpageJobIdRoute
  '/news/$year': typeof AuthNewsYearIndexRoute
  '/videos/fullpage': typeof AuthVideosFullpageIndexRoute
  '/news/$year/gallery/write': typeof AuthNewsYearGalleryWriteRoute
  '/news/$year/gallery': typeof AuthNewsYearGalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/awards': typeof AuthAwardsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/mypage/edit': typeof AuthMypageEditRoute
  '/_auth/mypage/password-change': typeof AuthMypagePasswordChangeRoute
  '/_auth/news/gallery': typeof AuthNewsGalleryRoute
  '/_auth/notice/$id': typeof AuthNoticeIdRoute
  '/_auth/notice/write': typeof AuthNoticeWriteRoute
  '/_auth/training/$id': typeof AuthTrainingIdRoute
  '/_auth/training/write': typeof AuthTrainingWriteRoute
  '/_auth/users/$id': typeof AuthUsersIdRoute
  '/_auth/videos/$id': typeof AuthVideosIdRoute
  '/_auth/mypage/': typeof AuthMypageIndexRoute
  '/_auth/news/': typeof AuthNewsIndexRoute
  '/_auth/notice/': typeof AuthNoticeIndexRoute
  '/_auth/training/': typeof AuthTrainingIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/videos/': typeof AuthVideosIndexRoute
  '/_auth/news/$year/$id': typeof AuthNewsYearIdRoute
  '/_auth/news/$year/write': typeof AuthNewsYearWriteRoute
  '/_auth/videos/fullpage/$jobId': typeof AuthVideosFullpageJobIdRoute
  '/_auth/news/$year/': typeof AuthNewsYearIndexRoute
  '/_auth/videos/fullpage/': typeof AuthVideosFullpageIndexRoute
  '/_auth/news/$year/gallery/write': typeof AuthNewsYearGalleryWriteRoute
  '/_auth/news/$year/gallery/': typeof AuthNewsYearGalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/login'
    | '/register'
    | '/mypage/edit'
    | '/mypage/password-change'
    | '/news/gallery'
    | '/notice/$id'
    | '/notice/write'
    | '/training/$id'
    | '/training/write'
    | '/users/$id'
    | '/videos/$id'
    | '/mypage/'
    | '/news/'
    | '/notice/'
    | '/training/'
    | '/users/'
    | '/videos/'
    | '/news/$year/$id'
    | '/news/$year/write'
    | '/videos/fullpage/$jobId'
    | '/news/$year/'
    | '/videos/fullpage/'
    | '/news/$year/gallery/write'
    | '/news/$year/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/login'
    | '/register'
    | '/mypage/edit'
    | '/mypage/password-change'
    | '/news/gallery'
    | '/notice/$id'
    | '/notice/write'
    | '/training/$id'
    | '/training/write'
    | '/users/$id'
    | '/videos/$id'
    | '/mypage'
    | '/news'
    | '/notice'
    | '/training'
    | '/users'
    | '/videos'
    | '/news/$year/$id'
    | '/news/$year/write'
    | '/videos/fullpage/$jobId'
    | '/news/$year'
    | '/videos/fullpage'
    | '/news/$year/gallery/write'
    | '/news/$year/gallery'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/awards'
    | '/_public/login'
    | '/_public/register'
    | '/_auth/'
    | '/_auth/mypage/edit'
    | '/_auth/mypage/password-change'
    | '/_auth/news/gallery'
    | '/_auth/notice/$id'
    | '/_auth/notice/write'
    | '/_auth/training/$id'
    | '/_auth/training/write'
    | '/_auth/users/$id'
    | '/_auth/videos/$id'
    | '/_auth/mypage/'
    | '/_auth/news/'
    | '/_auth/notice/'
    | '/_auth/training/'
    | '/_auth/users/'
    | '/_auth/videos/'
    | '/_auth/news/$year/$id'
    | '/_auth/news/$year/write'
    | '/_auth/videos/fullpage/$jobId'
    | '/_auth/news/$year/'
    | '/_auth/videos/fullpage/'
    | '/_auth/news/$year/gallery/write'
    | '/_auth/news/$year/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/awards': {
      id: '/_auth/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AuthAwardsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mypage/': {
      id: '/_auth/mypage/'
      path: '/mypage'
      fullPath: '/mypage/'
      preLoaderRoute: typeof AuthMypageIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mypage/edit': {
      id: '/_auth/mypage/edit'
      path: '/mypage/edit'
      fullPath: '/mypage/edit'
      preLoaderRoute: typeof AuthMypageEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mypage/password-change': {
      id: '/_auth/mypage/password-change'
      path: '/mypage/password-change'
      fullPath: '/mypage/password-change'
      preLoaderRoute: typeof AuthMypagePasswordChangeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/': {
      id: '/_auth/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AuthNewsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/gallery': {
      id: '/_auth/news/gallery'
      path: '/news/gallery'
      fullPath: '/news/gallery'
      preLoaderRoute: typeof AuthNewsGalleryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notice/': {
      id: '/_auth/notice/'
      path: '/notice'
      fullPath: '/notice/'
      preLoaderRoute: typeof AuthNoticeIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notice/$id': {
      id: '/_auth/notice/$id'
      path: '/notice/$id'
      fullPath: '/notice/$id'
      preLoaderRoute: typeof AuthNoticeIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notice/write': {
      id: '/_auth/notice/write'
      path: '/notice/write'
      fullPath: '/notice/write'
      preLoaderRoute: typeof AuthNoticeWriteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/training/': {
      id: '/_auth/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof AuthTrainingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/training/$id': {
      id: '/_auth/training/$id'
      path: '/training/$id'
      fullPath: '/training/$id'
      preLoaderRoute: typeof AuthTrainingIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/training/write': {
      id: '/_auth/training/write'
      path: '/training/write'
      fullPath: '/training/write'
      preLoaderRoute: typeof AuthTrainingWriteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$id': {
      id: '/_auth/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthUsersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/videos/': {
      id: '/_auth/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AuthVideosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/videos/$id': {
      id: '/_auth/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof AuthVideosIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/$year/': {
      id: '/_auth/news/$year/'
      path: '/news/$year'
      fullPath: '/news/$year/'
      preLoaderRoute: typeof AuthNewsYearIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/$year/$id': {
      id: '/_auth/news/$year/$id'
      path: '/news/$year/$id'
      fullPath: '/news/$year/$id'
      preLoaderRoute: typeof AuthNewsYearIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/$year/write': {
      id: '/_auth/news/$year/write'
      path: '/news/$year/write'
      fullPath: '/news/$year/write'
      preLoaderRoute: typeof AuthNewsYearWriteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/videos/fullpage/': {
      id: '/_auth/videos/fullpage/'
      path: '/videos/fullpage'
      fullPath: '/videos/fullpage/'
      preLoaderRoute: typeof AuthVideosFullpageIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/videos/fullpage/$jobId': {
      id: '/_auth/videos/fullpage/$jobId'
      path: '/videos/fullpage/$jobId'
      fullPath: '/videos/fullpage/$jobId'
      preLoaderRoute: typeof AuthVideosFullpageJobIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/$year/gallery/': {
      id: '/_auth/news/$year/gallery/'
      path: '/news/$year/gallery'
      fullPath: '/news/$year/gallery/'
      preLoaderRoute: typeof AuthNewsYearGalleryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news/$year/gallery/write': {
      id: '/_auth/news/$year/gallery/write'
      path: '/news/$year/gallery/write'
      fullPath: '/news/$year/gallery/write'
      preLoaderRoute: typeof AuthNewsYearGalleryWriteRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAwardsRoute: typeof AuthAwardsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthMypageEditRoute: typeof AuthMypageEditRoute
  AuthMypagePasswordChangeRoute: typeof AuthMypagePasswordChangeRoute
  AuthNewsGalleryRoute: typeof AuthNewsGalleryRoute
  AuthNoticeIdRoute: typeof AuthNoticeIdRoute
  AuthNoticeWriteRoute: typeof AuthNoticeWriteRoute
  AuthTrainingIdRoute: typeof AuthTrainingIdRoute
  AuthTrainingWriteRoute: typeof AuthTrainingWriteRoute
  AuthUsersIdRoute: typeof AuthUsersIdRoute
  AuthVideosIdRoute: typeof AuthVideosIdRoute
  AuthMypageIndexRoute: typeof AuthMypageIndexRoute
  AuthNewsIndexRoute: typeof AuthNewsIndexRoute
  AuthNoticeIndexRoute: typeof AuthNoticeIndexRoute
  AuthTrainingIndexRoute: typeof AuthTrainingIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthVideosIndexRoute: typeof AuthVideosIndexRoute
  AuthNewsYearIdRoute: typeof AuthNewsYearIdRoute
  AuthNewsYearWriteRoute: typeof AuthNewsYearWriteRoute
  AuthVideosFullpageJobIdRoute: typeof AuthVideosFullpageJobIdRoute
  AuthNewsYearIndexRoute: typeof AuthNewsYearIndexRoute
  AuthVideosFullpageIndexRoute: typeof AuthVideosFullpageIndexRoute
  AuthNewsYearGalleryWriteRoute: typeof AuthNewsYearGalleryWriteRoute
  AuthNewsYearGalleryIndexRoute: typeof AuthNewsYearGalleryIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAwardsRoute: AuthAwardsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthMypageEditRoute: AuthMypageEditRoute,
  AuthMypagePasswordChangeRoute: AuthMypagePasswordChangeRoute,
  AuthNewsGalleryRoute: AuthNewsGalleryRoute,
  AuthNoticeIdRoute: AuthNoticeIdRoute,
  AuthNoticeWriteRoute: AuthNoticeWriteRoute,
  AuthTrainingIdRoute: AuthTrainingIdRoute,
  AuthTrainingWriteRoute: AuthTrainingWriteRoute,
  AuthUsersIdRoute: AuthUsersIdRoute,
  AuthVideosIdRoute: AuthVideosIdRoute,
  AuthMypageIndexRoute: AuthMypageIndexRoute,
  AuthNewsIndexRoute: AuthNewsIndexRoute,
  AuthNoticeIndexRoute: AuthNoticeIndexRoute,
  AuthTrainingIndexRoute: AuthTrainingIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthVideosIndexRoute: AuthVideosIndexRoute,
  AuthNewsYearIdRoute: AuthNewsYearIdRoute,
  AuthNewsYearWriteRoute: AuthNewsYearWriteRoute,
  AuthVideosFullpageJobIdRoute: AuthVideosFullpageJobIdRoute,
  AuthNewsYearIndexRoute: AuthNewsYearIndexRoute,
  AuthVideosFullpageIndexRoute: AuthVideosFullpageIndexRoute,
  AuthNewsYearGalleryWriteRoute: AuthNewsYearGalleryWriteRoute,
  AuthNewsYearGalleryIndexRoute: AuthNewsYearGalleryIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
