packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true

catalog:
  "react": "^18.2.0"
  "react-dom": "^18.2.0"
  "@types/react": "^18.0.29"
  "@types/react-dom": "^18.0.11"
  "typescript": "^5.9.3"
