/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as InternalSplatRouteImport } from './routes/[_]internal.$'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NoticeIndexRouteImport } from './routes/notice.index'
import { Route as NoticeIdRouteImport } from './routes/notice.$id'
import { Route as PhotoIndexRouteImport } from './routes/photo.index'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as NewsIdIndexRouteImport } from './routes/news.$id.index'
import { Route as NewsIdNewsIdRouteImport } from './routes/news.$id.$newsId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSplatRoute = InternalSplatRouteImport.update({
  id: '/_internal/$',
  path: '/_internal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeIndexRoute = NoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeIdRoute = NoticeIdRouteImport.update({
  id: '/notice/$id',
  path: '/notice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIndexRoute = PhotoIndexRouteImport.update({
  id: '/photo/',
  path: '/photo/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdIndexRoute = NewsIdIndexRouteImport.update({
  id: '/news/$id/',
  path: '/news/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdNewsIdRoute = NewsIdNewsIdRouteImport.update({
  id: '/news/$id/$newsId',
  path: '/news/$id/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/album': typeof AlbumRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_internal/$': typeof InternalSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/notice/$id': typeof NoticeIdRoute
  '/photo/$id': typeof PhotoIdRoute
  '/news/': typeof NewsIndexRoute
  '/notice/': typeof NoticeIndexRoute
  '/photo/': typeof PhotoIndexRoute
  '/news/$id/$newsId': typeof NewsIdNewsIdRoute
  '/news/$id/': typeof NewsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/album': typeof AlbumRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_internal/$': typeof InternalSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/notice/$id': typeof NoticeIdRoute
  '/photo/$id': typeof PhotoIdRoute
  '/news': typeof NewsIndexRoute
  '/notice': typeof NoticeIndexRoute
  '/photo': typeof PhotoIndexRoute
  '/news/$id/$newsId': typeof NewsIdNewsIdRoute
  '/news/$id': typeof NewsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/album': typeof AlbumRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_internal/$': typeof InternalSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/notice/$id': typeof NoticeIdRoute
  '/photo/$id': typeof PhotoIdRoute
  '/news/': typeof NewsIndexRoute
  '/notice/': typeof NoticeIndexRoute
  '/photo/': typeof PhotoIndexRoute
  '/news/$id/$newsId': typeof NewsIdNewsIdRoute
  '/news/$id/': typeof NewsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/album'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_internal/$'
    | '/api/$'
    | '/notice/$id'
    | '/photo/$id'
    | '/news/'
    | '/notice/'
    | '/photo/'
    | '/news/$id/$newsId'
    | '/news/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/album'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_internal/$'
    | '/api/$'
    | '/notice/$id'
    | '/photo/$id'
    | '/news'
    | '/notice'
    | '/photo'
    | '/news/$id/$newsId'
    | '/news/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/album'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_internal/$'
    | '/api/$'
    | '/notice/$id'
    | '/photo/$id'
    | '/news/'
    | '/notice/'
    | '/photo/'
    | '/news/$id/$newsId'
    | '/news/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlbumRoute: typeof AlbumRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  InternalSplatRoute: typeof InternalSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  NoticeIdRoute: typeof NoticeIdRoute
  PhotoIdRoute: typeof PhotoIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NoticeIndexRoute: typeof NoticeIndexRoute
  PhotoIndexRoute: typeof PhotoIndexRoute
  NewsIdNewsIdRoute: typeof NewsIdNewsIdRoute
  NewsIdIndexRoute: typeof NewsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal/$': {
      id: '/_internal/$'
      path: '/_internal/$'
      fullPath: '/_internal/$'
      preLoaderRoute: typeof InternalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice/': {
      id: '/notice/'
      path: '/notice'
      fullPath: '/notice/'
      preLoaderRoute: typeof NoticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice/$id': {
      id: '/notice/$id'
      path: '/notice/$id'
      fullPath: '/notice/$id'
      preLoaderRoute: typeof NoticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/': {
      id: '/photo/'
      path: '/photo'
      fullPath: '/photo/'
      preLoaderRoute: typeof PhotoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id/': {
      id: '/news/$id/'
      path: '/news/$id'
      fullPath: '/news/$id/'
      preLoaderRoute: typeof NewsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id/$newsId': {
      id: '/news/$id/$newsId'
      path: '/news/$id/$newsId'
      fullPath: '/news/$id/$newsId'
      preLoaderRoute: typeof NewsIdNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlbumRoute: AlbumRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  InternalSplatRoute: InternalSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  NoticeIdRoute: NoticeIdRoute,
  PhotoIdRoute: PhotoIdRoute,
  NewsIndexRoute: NewsIndexRoute,
  NoticeIndexRoute: NoticeIndexRoute,
  PhotoIndexRoute: PhotoIndexRoute,
  NewsIdNewsIdRoute: NewsIdNewsIdRoute,
  NewsIdIndexRoute: NewsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
