import { defineConfig, QueryOptions } from "orval";
import responseTransformer from "./orval.transformer";

const IS_PROD = process.env.NODE_ENV === "production";

const docTargets = IS_PROD
  ? {
      v2Api: "https://api.uosjudo.com/api/docs/v2-api/json",
      v2Admin: "https://api.uosjudo.com/api/docs/v2-admin/json",
    }
  : {
      v2Api: "http://localhost:4000/api/docs/v2-api/json",
      v2Admin: "http://localhost:4000/api/docs/v2-admin/json",
    };

const baseUrl = IS_PROD ? "https://api.uosjudo.com" : "http://localhost:4000";

const baseQueryOptions = {
  version: 5,
  useInfinite: true,
  usePrefetch: true,
  useSuspenseQuery: true,
  useInvalidate: true,
  // 요청 함수(listBoards 등)도 내보낸다. 커서/오프셋을 직접 넘기는 무한 쿼리는
  // 생성된 훅으로 만들 수 없어서(생성된 infinite queryFn 은 pageParam 을 무시한다)
  // 소비자가 요청 함수를 직접 감싸야 한다.
  shouldExportHttpClient: true,
  shouldExportQueryKey: true,
  shouldSplitQueryKey: true,
} as const;

// NOTE: orval's method-based hook selection is fragile when the useQuery/
// useMutation booleans are set explicitly:
//   - `useQuery: true` forces EVERY operation (incl. POST/PUT/DELETE) to be a
//     query hook → mutations lose `.mutate` ("o.mutate is not a function").
//   - `useMutation: true` on an all-GET spec forces every GET into a mutation
//     → no `*QueryOptions`/suspense hooks ("(void 0) is not a function").
//
// v2Api used to be entirely read-only, so it forced `useQuery: true`. The
// 게시글 반응(좋아요) API added PUT/DELETE to this spec, and that flag would drag
// them into query hooks too — so both flags are now left unset here as well and
// orval decides per HTTP method.
//
// v2Admin is mixed (GET + write endpoints) and has always relied on that.
const apiQueryOptions: QueryOptions = {
  ...baseQueryOptions,
};

const adminQueryOptions: QueryOptions = {
  ...baseQueryOptions,
};

// NOTE: 생성 파일 상단에 `// @ts-nocheck` 를 넣어 생성 코드 내부는 앱 type-check
// 대상에서 제외한다 (예: multipart formData.append 에 unknown 타입을 넘기는
// orval 생성 코드가 strict 모드에서 TS2769 를 낸다). export 된 타입 시그니처는
// 그대로 살아 있으므로 소비자 코드의 타입 검사에는 영향이 없다.
// 문자열을 반환하면 orval 이 verbatim 으로 삽입한다 (배열은 jsDoc 블록으로 감싸
// `// @ts-nocheck` 가 동작하지 않으니 반드시 문자열이어야 한다).
const filesHeader = (info: { title?: string; version?: string }) =>
  [
    "/**",
    " * Generated by orval 🍺 - Do not edit manually.",
    ...(info.title ? [` * ${info.title}`] : []),
    ...(info.version ? [` * OpenAPI spec version: ${info.version}`] : []),
    " */",
    "// @ts-nocheck",
    "",
  ].join("\n");

export default defineConfig({
  v2Api: {
    input: {
      target: docTargets.v2Api,
    },
    output: {
      target: "src/_generated/v2/api/index.ts",
      schemas: "src/_generated/v2/api/model",
      client: "react-query",
      httpClient: "axios",
      clean: true,
      baseUrl,
      override: {
        transformer: responseTransformer,
        query: apiQueryOptions,
        header: filesHeader,
      },
    },
  },
  v2Admin: {
    input: {
      target: docTargets.v2Admin,
    },
    output: {
      target: "src/_generated/v2/admin/index.ts",
      schemas: "src/_generated/v2/admin/model",
      client: "react-query",
      httpClient: "axios",
      clean: true,
      baseUrl,
      override: {
        transformer: responseTransformer,
        query: adminQueryOptions,
        header: filesHeader,
      },
    },
  },
});
